# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.3"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements.txt --use-mirrors
  - pip install sphinx --use-mirrors

# command to run tests, e.g. python setup.py test
script:
  - sphinx-build -b linkcheck ./ _build/
  - sphinx-build -b doctest ./ _build/
  - sphinx-build -b html ./ _build/