# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.6"

# command to install dependencies, e.g. pip install -r requirements.txt
install: 
  - pip install sphinx
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - sphinx-build -b linkcheck ./ _build/
  - sphinx-build -b doctest ./ _build/
  - sphinx-build -b html ./ _build/
